language: minimal
sudo: required

git:
  submodules: false

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.mafia

matrix:
  include:
  - env: GHCVER=8.2.2 CABALVER=1.24
    addons:
      apt:
        update: true
        sources:
          - hvr-ghc
        packages:
          - ghc-8.2.2
          - cabal-install-1.24
  - env: GHCVER=8.2.2 CABALVER=2.0
    addons:
      apt:
        update: true
        sources:
          - hvr-ghc
        packages:
          - ghc-8.2.2
          - cabal-install-2.0
  - env: GHCVER=8.4.4 CABALVER=2.0
    addons:
      apt:
        update: true
        sources:
          - hvr-ghc
        packages:
          - ghc-8.4.4
          - cabal-install-2.0

  #allow-failures:
  #  - env: GHCVER=head
addons:
  apt:
    update: true
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.2
      - libgmp-dev

before_install:
  # ghc
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

script:
  - bin/ci

notifications:
  slack:
    secure: lNtxBYWZgtL7lrAIvIFONFozbakG85KRrfv7SCsapyj63CS60FzScrY3OUA8gCJ9ggkysnxcmrN0ZJP8Gswly+z46edw983tqxX+VXVXrKCuNn/dMIlE5FJMbeQf5cQoVbHNyLfh7Wq/00z3w5IsTJfIGcP8DOPvSy/BraMC94L9mP9FEuSLDleoQWbyi3Qbi9K5LpUivPDFZCF8bsoS+HiFTCpE3lDjx8LAa0JvKtsp9cHnyjrDsU5wz63/4sfq3kOtu2tDyE9F27F9TwiD0lnyz+Yq9+naBO2Gfj2tL3kfvHjQKfnlyVVHu6zGqw+bW7DH5SHq7j9zRI9KqXLXXNRjygjMH3IqQR0xjYvEd7du1ONsd6MJckM/IiD5HeM1AP7F6zKctNZP0Xn5SxVKcub/8MndYGOzO4WKZwJEUxNmzfgWmKeoYkh16vqFRqjR0XQCUiJj0gHRgihS5wNIqFlwpe2cxZRvP/BCEJilApHdSpZ5DF3SVcCDkjWy7mBC0xwDUBAW+q3q86YnCzWU9R1WfTEURkhBaLKI1cYhmjidpZUWeZKuaHbmr1Il2zluxtWj3U96o7F9/5CfLzTpCSj8fZfuXW4RBSoD9LzlmJHSyUiFC+Mmc2ho7wKcU8tnDTFljeDRxqsmK03773hUAjaiAfC7YvaXig399dI/Ah8=
